// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/giacomo/caendgz-sipmanalysis/macro/04_multi_scan/./sipm_tot_analysis.cpp";

#endif
